workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Create iOS Platform Folder
        script: |
          npx cap add ios || true

      - name: Fix permissions
        script: |
          chmod +x ./node_modules/.bin/cap || true

      - name: Sync Capacitor Assets
        script: |
          npx cap sync ios

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa